/**
 * Builds the content of the ESM runner script that gets written to disk
 * and executed inside the user's AdonisJS project directory.
 *
 * The runner:
 *  1. Bootstraps AdonisJS via Ignitor
 *  2. Hooks Lucid's query events for SQL capture
 *  3. Captures console.log/error/warn output
 *  4. Executes the user's code in an async IIFE
 *  5. Serializes the result and writes JSON to stdout
 *  6. Terminates the AdonisJS app
 */
export function buildRunnerContent(userCode: string): string {
  // Escape any backticks in the user code to avoid breaking the template literal
  // We use string concatenation in the runner instead of template literals for user code
  return `
// AUTO-GENERATED by AdonisJS Tinkerr — DO NOT EDIT OR COMMIT
import { pathToFileURL } from 'node:url'
import { Ignitor } from '@adonisjs/core'

const __startTime = Date.now()

// ── Serializer ─────────────────────────────────────────────────────────────
function __serialize(value, seen) {
  if (!seen) seen = new Set()
  if (value === null || value === undefined) return value
  if (typeof value === 'bigint') return String(value) + 'n'
  if (value instanceof Date) return { __type: 'Date', value: value.toISOString() }
  if (typeof value === 'function') return '[Function: ' + (value.name || 'anonymous') + ']'
  if (typeof value !== 'object') return value
  if (seen.has(value)) return '[Circular]'
  seen.add(value)
  // Lucid models expose serialize() or toJSON()
  if (typeof value.serialize === 'function') {
    try { return __serialize(value.serialize(), seen) } catch {}
  }
  if (typeof value.toJSON === 'function') {
    try { return __serialize(value.toJSON(), seen) } catch {}
  }
  if (Array.isArray(value)) {
    if (value.length > 1000) {
      const truncated = value.slice(0, 1000).map(v => __serialize(v, seen))
      truncated.push('[... ' + (value.length - 1000) + ' more items truncated]')
      return truncated
    }
    return value.map(v => __serialize(v, seen))
  }
  const result = {}
  for (const [k, v] of Object.entries(value)) {
    result[k] = __serialize(v, seen)
  }
  return result
}

// ── Bootstrap AdonisJS ─────────────────────────────────────────────────────
// pathToFileURL handles Windows paths (C:\\ → file:///C:/) correctly
const __rootUrl = new URL(pathToFileURL(process.cwd()).href + '/')
// Pass importer so providers can call app.import() to dynamically load modules
const __ignitor = new Ignitor(__rootUrl, { importer: (moduleId) => import(moduleId) })
const __app = __ignitor.createApp('repl')

try {
  await __app.init()
  await __app.boot()
} catch (__bootErr) {
  process.stdout.write(JSON.stringify({
    success: false,
    error: {
      message: 'AdonisJS app failed to boot: ' + __bootErr.message,
      stack: __bootErr.stack || ''
    },
    logs: [],
    queries: [],
    duration: Date.now() - __startTime
  }))
  process.exit(1)
}

// ── SQL Query Capture ──────────────────────────────────────────────────────
const __queries = []
try {
  const { default: db } = await import('@adonisjs/lucid/services/db')
  db.on('query', (__log) => {
    __queries.push({
      sql: __log.sql,
      bindings: __log.bindings ?? [],
      duration: typeof __log.duration === 'number' ? __log.duration : null
    })
  })
} catch {
  // Lucid is not installed in this project — that's fine
}

// ── Console Capture ────────────────────────────────────────────────────────
const __logs = []
const __origLog   = console.log.bind(console)
const __origError = console.error.bind(console)
const __origWarn  = console.warn.bind(console)
console.log   = (...args) => __logs.push({ level: 'log',   args: args.map(a => __serialize(a)) })
console.error = (...args) => __logs.push({ level: 'error', args: args.map(a => __serialize(a)) })
console.warn  = (...args) => __logs.push({ level: 'warn',  args: args.map(a => __serialize(a)) })

// ── User Code ──────────────────────────────────────────────────────────────
let __result, __userError
try {
  __result = await (async () => {
${userCode}
  })()
} catch (__e) {
  __userError = { message: __e.message, stack: __e.stack || '' }
}

// ── Restore Console ────────────────────────────────────────────────────────
console.log   = __origLog
console.error = __origError
console.warn  = __origWarn

// ── Write Output ───────────────────────────────────────────────────────────
const __output = __userError
  ? {
      success: false,
      error: __userError,
      logs: __logs,
      queries: __queries,
      duration: Date.now() - __startTime
    }
  : {
      success: true,
      result: __serialize(__result),
      logs: __logs,
      queries: __queries,
      duration: Date.now() - __startTime
    }

process.stdout.write(JSON.stringify(__output))

// ── Terminate App ──────────────────────────────────────────────────────────
// Race against a 5s timeout in case DB pool or other resources hang
await Promise.race([
  __app.terminate(),
  new Promise(resolve => setTimeout(resolve, 5000))
])
process.exit(0)
`.trimStart()
}
