/**
 * Generates the persistent worker script that runs inside the user's AdonisJS
 * project directory.
 *
 * The worker:
 *  1. Boots AdonisJS once and keeps it alive
 *  2. Hooks into the Knex client directly for SQL capture (works regardless of
 *     the project's database debug setting)
 *  3. Reads newline-delimited JSON { id, code } requests from stdin
 *  4. Executes user code via AsyncFunction (same scope/module context as the
 *     worker, so console capture and import() resolution both work correctly)
 *  5. Writes newline-delimited JSON results to stdout
 *  6. Terminates the AdonisJS app on SIGTERM
 */
export function buildWorkerContent(): string {
  return `
// AUTO-GENERATED by AdonisJS Tinkerr Worker — DO NOT EDIT OR COMMIT
import { pathToFileURL } from 'node:url'
import { createInterface } from 'node:readline'
import { Ignitor } from '@adonisjs/core'

// ── Serializer ─────────────────────────────────────────────────────────────
function __serialize(value, seen) {
  if (!seen) seen = new Set()
  if (value === null || value === undefined) return value
  if (typeof value === 'bigint') return String(value) + 'n'
  if (value instanceof Date) return { __type: 'Date', value: value.toISOString() }
  if (typeof value === 'function') return '[Function: ' + (value.name || 'anonymous') + ']'
  if (typeof value !== 'object') return value
  if (seen.has(value)) return '[Circular]'
  seen.add(value)
  if (typeof value.serialize === 'function') {
    try { return __serialize(value.serialize(), seen) } catch {}
  }
  if (typeof value.toJSON === 'function') {
    try { return __serialize(value.toJSON(), seen) } catch {}
  }
  if (Array.isArray(value)) {
    if (value.length > 1000) {
      const truncated = value.slice(0, 1000).map(v => __serialize(v, seen))
      truncated.push('[... ' + (value.length - 1000) + ' more items truncated]')
      return truncated
    }
    return value.map(v => __serialize(v, seen))
  }
  const result = {}
  for (const [k, v] of Object.entries(value)) {
    result[k] = __serialize(v, seen)
  }
  return result
}

// ── Bootstrap AdonisJS ─────────────────────────────────────────────────────
const __rootUrl = new URL(pathToFileURL(process.cwd()).href + '/')
const __ignitor = new Ignitor(__rootUrl, { importer: (moduleId) => import(moduleId) })
const __app = __ignitor.createApp('repl')

try {
  await __app.init()
  await __app.boot()
} catch (__bootErr) {
  process.stdout.write(JSON.stringify({ type: 'boot-error', error: { message: __bootErr.message, stack: __bootErr.stack || '' } }) + '\\n')
  process.exit(1)
}

// ── SQL Query Capture ──────────────────────────────────────────────────────
// We hook into the underlying Knex client directly. This works regardless of
// whether the project has debug: true in its database config. Lucid only
// forwards query events to the AdonisJS emitter when debug mode is on, so
// the emitter approach silently misses queries in most projects.
let __queries = []
const __queryStartTimes = new Map()

try {
  const { default: db } = await import('@adonisjs/lucid/services/db')
  // getWriteClient() returns the raw Knex instance for the default connection.
  // This forces the connection pool to initialise, which is acceptable here
  // since the app has already booted and a DB connection will be needed anyway.
  const __knex = db.connection().getWriteClient()

  __knex.on('query', (__log) => {
    __queryStartTimes.set(__log.__knexQueryUid, Date.now())
    __queries.push({
      __uid: __log.__knexQueryUid,
      sql: __log.sql,
      bindings: __log.bindings ?? [],
      duration: null,
    })
  })

  __knex.on('query-response', (_res, __log) => {
    const __t0 = __queryStartTimes.get(__log.__knexQueryUid)
    if (__t0 !== undefined) {
      __queryStartTimes.delete(__log.__knexQueryUid)
      // Find the most-recent matching query and fill in the duration
      for (let __i = __queries.length - 1; __i >= 0; __i--) {
        if (__queries[__i].__uid === __log.__knexQueryUid) {
          __queries[__i].duration = Date.now() - __t0
          break
        }
      }
    }
  })

  __knex.on('query-error', (_err, __log) => {
    __queryStartTimes.delete(__log.__knexQueryUid)
  })
} catch {
  // Lucid not installed in this project — that's fine, queries stay empty
}

// ── Signal Ready ───────────────────────────────────────────────────────────
process.stdout.write(JSON.stringify({ type: 'ready' }) + '\\n')

// ── Request Loop ───────────────────────────────────────────────────────────
// User code runs via AsyncFunction so it executes in the same global/module
// context as this worker. That means:
//   - console.log overrides apply immediately (no cross-module global issues)
//   - import() resolves relative to process.cwd() (= the AdonisJS project root)
//   - AdonisJS service container imports (e.g. #models/user) work correctly
const __AsyncFunction = Object.getPrototypeOf(async function () {}).constructor

const __rl = createInterface({ input: process.stdin, crlfDelay: Infinity })

__rl.on('line', async (line) => {
  const trimmed = line.trim()
  if (!trimmed) return

  let __msg
  try { __msg = JSON.parse(trimmed) } catch { return }

  const { id, code } = __msg
  const __startTime = Date.now()

  // Reset per-execution query/log state
  __queries = []
  __queryStartTimes.clear()
  const __logs = []

  // Capture console output — AsyncFunction shares the same global console
  const __origLog   = console.log
  const __origError = console.error
  const __origWarn  = console.warn
  console.log   = (...args) => { __logs.push({ level: 'log',   args: args.map(a => __serialize(a)) }) }
  console.error = (...args) => { __logs.push({ level: 'error', args: args.map(a => __serialize(a)) }) }
  console.warn  = (...args) => { __logs.push({ level: 'warn',  args: args.map(a => __serialize(a)) }) }

  let __result, __userError
  try {
    __result = await new __AsyncFunction(code)()
  } catch (__e) {
    __userError = { message: __e.message, stack: __e.stack || '' }
  } finally {
    console.log   = __origLog
    console.error = __origError
    console.warn  = __origWarn
  }

  // Strip internal __uid tracking field before sending
  const __outQueries = __queries.map(({ __uid: _, ...q }) => q)

  const __memoryUsed = process.memoryUsage().heapUsed
  const __output = __userError
    ? { type: 'result', id, success: false, error: __userError, logs: __logs, queries: __outQueries, duration: Date.now() - __startTime, memoryUsed: __memoryUsed }
    : { type: 'result', id, success: true,  result: __serialize(__result), logs: __logs, queries: __outQueries, duration: Date.now() - __startTime, memoryUsed: __memoryUsed }

  process.stdout.write(JSON.stringify(__output) + '\\n')
})

// ── Graceful Shutdown ──────────────────────────────────────────────────────
process.on('SIGTERM', async () => {
  await Promise.race([
    __app.terminate(),
    new Promise(resolve => setTimeout(resolve, 3000))
  ])
  process.exit(0)
})
`.trimStart()
}
